language: python
python:
    - 2.7
    - 3.5
    - 3.6

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - solida -v
  - solida list
  - solida pipeline -l dima -p dima
  - solida pipeline -l dima -p dima --create-profile
  - solida pipeline -l dima -p dima --deploy