---

- name: Replace path to the config_file into the Snakemake file
  replace:
    dest: "{{ pipeline_dir }}/Snakefile"
    regexp: "{{ project_config_file }}"
    replace: "{{ pipeline_dir }}/{{ project_config_file }}"
  ignore_errors: yes

- name: Replace path to samples.tsv into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: "samples.tsv"
    replace: "{{ pipeline_dir }}/samples.tsv"
  ignore_errors: yes

- name: Replace path to units.tsv into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: "units.tsv"
    replace: "{{ pipeline_dir }}/units.tsv"
  ignore_errors: yes

- name: Replace path_to_references_data into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_references_data'
    replace: "{{ references_dir }}"
  ignore_errors: yes

- name: Replace reference provider into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: '_provider_'
    replace: "{{ references_provider }}"
  ignore_errors: yes

- name: Replace reference fasta file into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: '_genome_fasta_'
    replace: "{{ reference_genome_fasta }}"
  ignore_errors: yes

- name: Replace reference release into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: '_release_'
    replace: "{{ references_release }}"
  ignore_errors: yes

- name: Find tsv files
  find:
    paths: "{{ pipeline_dir }}"
    patterns: '*.tsv'
  register: tsv_files

- name: Replace path_to_datasets into the project configuration file
  replace:
    dest: "{{ item.path }}"
    regexp: 'path_to_datasets'
    replace: "{{ datasets_dir }}"
  loop: "{{ tsv_files.files }}"
  ignore_errors: yes

- name: Replace path_to_tmp_dir into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_tmp_dir'
    replace: "{{ tmp_dir }}"
  ignore_errors: yes

- name: Replace path_to_software into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_software-kggseq.jar'
    replace: "{{ kggseq_path }}"
  ignore_errors: yes

- name: Replace path_to_blocks_file into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_blocks_file'
    replace: "{{ blocks_file }}"
  ignore_errors: yes

- name: Replace path_to_ped_file into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_ped_file'
    replace: "{{ ped_file }}"
  ignore_errors: yes

- name: Replace path_to_reheader_file into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_reheader_file'
    replace: "{{ reheader_file }}"
  ignore_errors: yes

- name: Replace path_to_recalibrated_vcf into the project configuration file
  replace:
    dest: "{{ pipeline_dir }}/{{ project_config_file }}"
    regexp: 'path_to_recalibrated_vcf'
    replace: "{{ recalibrated_vcf_file }}"
  ignore_errors: yes



